# Generated by Django 5.1.6 on 2025-02-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_post_delete_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='word_count',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
