# Generated by Django 5.1.6 on 2025-02-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_post_word_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='word_count',
            field=models.IntegerField(max_length=200),
        ),
    ]
