# Generated by Django 5.1.6 on 2025-02-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_post_word_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
